# Generated by Django 5.2.7 on 2025-10-28 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_chefs'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chefs',
        ),
    ]
