# Generated by Django 5.2.7 on 2025-12-19 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_delete_chefs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('main', 'Main'), ('appetizer', 'Appetizer'), ('dessert', 'Dessert'), ('beverage', 'Beverage')], default='main', max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='flightstaff',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='flightstaff',
            name='staff',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='origin',
        ),
        migrations.AddField(
            model_name='flight',
            name='connecting_flight_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='distance_km',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='shared_airline',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='shared_flight_number',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='affiliated_passengers',
            field=models.ManyToManyField(blank=True, related_name='affiliates', to='flights.passenger'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AddField(
            model_name='passenger',
            name='gender',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='passenger',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='infants', to='flights.passenger'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='passenger',
            name='seat_type',
            field=models.CharField(blank=True, choices=[('business', 'Business'), ('economy', 'Economy')], default='economy', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.flight'),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='flights.passenger'),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='seat_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='flightticket',
            name='ticket_class',
            field=models.CharField(blank=True, choices=[('Economy', 'Economy'), ('Business', 'Business'), ('First', 'First')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='destination_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='flights.airport'),
        ),
        migrations.AddField(
            model_name='flight',
            name='origin_airport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='flights.airport'),
        ),
        migrations.CreateModel(
            name='PlaneType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('total_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('business_seats', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('economy_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('seat_layout', models.JSONField(blank=True, default=dict, null=True)),
                ('max_cabin_crew', models.PositiveIntegerField(default=20)),
                ('min_cabin_crew', models.PositiveIntegerField(default=4)),
                ('standard_menu', models.ManyToManyField(blank=True, related_name='plane_types', to='flights.menuitem')),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('known_languages', models.JSONField(default=list)),
                ('max_range_km', models.PositiveIntegerField(blank=True, null=True)),
                ('seniority', models.CharField(blank=True, choices=[('senior', 'Senior'), ('junior', 'Junior'), ('trainee', 'Trainee')], max_length=10, null=True)),
                ('vehicle_restriction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pilots', to='flights.planetype')),
            ],
        ),
        migrations.CreateModel(
            name='CabinCrew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=100)),
                ('known_languages', models.JSONField(default=list)),
                ('role', models.CharField(choices=[('chief', 'Chief'), ('regular', 'Regular'), ('chef', 'Chef')], max_length=10)),
                ('seniority', models.CharField(choices=[('senior', 'Senior'), ('junior', 'Junior')], max_length=10)),
                ('recipes', models.ManyToManyField(blank=True, related_name='chefs', to='flights.menuitem')),
                ('vehicle_restrictions', models.ManyToManyField(blank=True, related_name='cabin_crews', to='flights.planetype')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='plane_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.planetype'),
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backend', models.CharField(choices=[('sql', 'SQL'), ('nosql', 'NoSQL')], default='sql', max_length=10)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rosters', to=settings.AUTH_USER_MODEL)),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rosters', to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='RosterCrewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crew_type', models.CharField(choices=[('pilot', 'Pilot'), ('cabin', 'Cabin Crew')], max_length=10)),
                ('assigned_role', models.CharField(blank=True, default='', max_length=50)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('cabin_crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.cabincrew')),
                ('pilot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='flights.pilot')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crew_assignments', to='flights.roster')),
            ],
        ),
        migrations.CreateModel(
            name='RosterPassengerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(blank=True, max_length=10, null=True)),
                ('seat_type', models.CharField(default='economy', max_length=20)),
                ('is_infant', models.BooleanField(default=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.passenger')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_assignments', to='flights.roster')),
            ],
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
        migrations.DeleteModel(
            name='FlightStaff',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
